# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-08 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='delete_status_color',
            field=models.CharField(default='green', max_length=10, verbose_name='设置状态颜色'),
        ),
    ]
