# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-17 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_delete_status_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='关于我')),
            ],
            options={
                'verbose_name_plural': '关于我',
                'verbose_name': '关于我',
            },
        ),
    ]
